### PR TITLE
[WIP] TextKit2 NSTextLayoutManager

### PR DESCRIPTION
**Pull request by DominikBucher12**
Implement TextKit2 because bullet points and numbered list looking really cool... 

Need to use correctly TextKit2 API since it is a mess right now :D (getting int from debugDescription just to Proof the concept...) 

With this, adding numbered and ordered list on iOS 16+ should be easy peasy.

### CODE REVIEW

**Comment by DominikBucher12** [comment]
@danielsaidi need a little help in here... 

not a macOS developer, but it appears ` public let scrollView = RichTextView.scrollableTextView()` ruins setting custom stuff and the TextView is missing textlayoutManager, could you help me out? 😅

**Comment by danielsaidi** [comment]
@DominikBucher12 I'm going through my projects and noticed that you mentioned me - didn't see that before! How are your status with this? Are you still actively working with RTK features?

**Comment by martindufort** [comment]
Question: Why was this closed without being merged? Lack of time? Incomplete PR? 
Would really use bullet and numbered lists...

Thanks

**Comment by danielsaidi** [comment]
I'd love that as well, but the PR has been stale for some time, and has some merge conflicts. I'd be happy to re-open it when it becomes active again.

**Comment by DominikBucher12** [comment]
In some close future, I will hopefully get my hands on this and properly implement this, lets see how it goes.

**Pull request closed without merging**
