### PR TITLE
Added mac catalyst support

### PR DESCRIPTION
**Pull request by Mcrich23**
- Now can run as ios would on mac catalyst apps

### CODE REVIEW

**Comment by danielsaidi** [comment]
Oh my GOD, that's amazing - thank you! 💥

**Comment by danielsaidi** [comment]
Would be nice to find a way to define those rules in a cleaner way, now that they are so many.

**Comment by Mcrich23** [comment]
np @danielsaidi. Also, have you ever heard of SwiftLint. Not sure if that is what you are talking about, but it could help in general.

**Comment by Mcrich23** [comment]
@danielsaidi, about to blow your mind: #98

**Comment by danielsaidi** [comment]
You did!! 🤯

**Pull request merged**
