### PR TITLE
Deletes unused RichTextAttributeWriter+Styles file

### PR DESCRIPTION
**Pull request by DominikBucher12**
# What this PR do:
- Deletes unused RichTextAttributeWriter
# How to test it
- Compile the project.
# Where you can start
-  The file.

### CODE REVIEW

**Comment by danielsaidi** [comment]
You are correct in that this function isn't being used by the library, but it actually serves a purpose in that you can use it to reliably set a style for a given range in e.g. a mutable attributed string.

So I don't think it should be removed just because it's not being used in the project.

**Comment by danielsaidi** [comment]
I've optimized the code, added a missing strikethrough and made the function share more with the rich text view component version, so I'm closing this without action. I'll let you know once everything is up.

**Comment by DominikBucher12** [comment]
I just noticed the conflict and commit, thanks!

**Comment by danielsaidi** [comment]
Ok, I've pushed some cleanups and improvements. I will also add underline color at a new rich text color, to optimize the code even more.

**Comment by danielsaidi** [comment]
@DominikBucher12 I've added a bunch of additional functionality and optimized the code in places. Please have a look at the latest commit and its release notes. I'll continue with your PRs now.

**Pull request closed without merging**
