### PR TITLE
fixing foreground color problem

### PR DESCRIPTION
**Pull request by codaman**

### CODE REVIEW

**Comment by danielsaidi** [comment]
Hi @codaman 

Thank you for this! So if we remove these lines, saving the text color works on both iOS and macOS?

**Comment by mcihanbulbul** [comment]
Yes I tested it on both iOS and Mac. It is working

**Comment by danielsaidi** [comment]
That's amazing! The reason why I added it here was to use a color that supports dark mode, but perhaps the text editor can apply the label/text color only when it's set up with an empty text?

**Comment by danielsaidi** [comment]
I will take a look at it too - thank you so much for helping out with this!

**Comment by mcihanbulbul** [comment]
I thank you for making public this project.

**Comment by danielsaidi** [comment]
I've been busy with another project, but will look at this the next week 👍

**Review by danielsaidi — APPROVED** [review]

**Pull request merged**
