### PR TITLE
[WIP] Indent functionality

### PR DESCRIPTION
**Pull request by jamesbradleym**
Heya! Really grateful to have found your RichTextKit swift package, Daniel! I thought it would be great to add indentation, and eventually bullet points, so I've started implementing this in this fork!

This is very much a rough draft but I tried to follow the standards and practices you employed in the original package. I'm also still finding my way through xcode, github, and swiftui so please let me know if there are any questions/recommendations/comments from what you see! In it's current state there are some hiccups - namely an issue where when you return to a new line and hit either indent option and then begin to type, that indentation will apply to the previous line. Planning to smooth out that issue over the next couple days but I'm sure it's an easy enough bug to squash!

Thanks again!

### CODE REVIEW

**Comment by danielsaidi** [comment]
Hi @jamesbradleym 

Thank you so much for looking into this. I will take a look at it when I have time 👍

**Comment by jamesbradleym** [comment]
@danielsaidi Still working on trying to bring this up to fully implemented but I'm hitting a roadblock with indentation after a newline. 

If you provide a new character/string after a newline then changing the paragraph style attributes with an updated firstline head indent and head indent then it works, but if there is no new character or string to apply this styling to then it styles the previous line which the newline is technically part of in the NSAttributedString. Still investigating how to apply a style to characters following the newline where the cursor is sitting..

**Comment by jamesbradleym** [comment]
Additional testing shows this problem also persists with text alignment. When 1 newline is given at the end of a NSAttributedString alignment does not apply, after typing into the richtexteditor the alignment is applied to the previous line/paragraph. When 2 newlines are given following a visual paragraph these features work as expected.

**Comment by danielsaidi** [comment]
Hey @jamesbradleym - great finds! There are some platform-specifics that I'd love to iron out. Unfortunately, some of the changes have side-effects on other handling, so it's quite tricky. I need to dedicate a few full days on this soon.

**Comment by danielsaidi** [comment]
Hi again @jamesbradleym - I've been busy with other projects, but I'm very curious to hear about your progress with this.

**Comment by jamesbradleym** [comment]
Hey @danielsaidi , sorry for the delay here - I haven't had a chance to track down the unexpected indent behavior with this added functionality so I wouldn't say it's ready to be merged necessarily but I'd be grateful for any review or comments you may have!

**Comment by danielsaidi** [comment]
Perfect, I hope that I'll have time later in May 👍

**Comment by jamesbradleym** [comment]
I've had a chance to look at this more and I think I may be on to a solution though it feels a bit hacky.. will commit sometime this week when it's a bit more fleshed out hopefully

**Comment by danielsaidi** [comment]
Sounds great @jamesbradleym - just let me know when you want me to take a look at it. 👍

**Comment by jamesbradleym** [comment]
@danielsaidi still hunting down a proper method to work this in. This implementation has a hang-up when attempting to indent at a location without characters, such as after a new line or at the very beginning of a document without text. If I'm being honest the work around (at least for the 'after newline' condition, need to hone in on the beginning of document issue) it feels a bit hacky, unfortunately I wasn't able to get indentation to work without giving NSAttributedString a character to work with. So I've given it "\u{00A0}", a non-breaking space, the cursor position is kept right before this character so the UI updates as expected. However my first attempts at having this space removed resulted in the paragraph styling being removed as well because it was using that character to style.. 

Other indent situations work as expected, indenting within a paragraph, at the beginning of a paragraph, end of a paragraph, etc have not had issues.

It would be great to get your feedback on this, even in its current state, if you have an opportunity. It would be very helpful to get your insight on both solving this issue and also getting a better understanding of what level of resolution this would require before you'd be comfortable accepting the feature.

Thanks!

**Comment by danielsaidi** [comment]
Hi @jamesbradleym 

Wow, sounds like you've put quite a lot of time into it - that's amazing!

I am working with a client that uses RTK now, so I will have more time to put on this project. I'll have a look in a day or two 👍

**Comment by jamesbradleym** [comment]
Hey @danielsaidi ,

So scratch everything I just said, after taking a look at why the first indent of a blank document wasn't working I stumbled across the bug, I was creating a fresh style that had no reference to our current typingAttributes paragraph style! I fixed this and it led me to the solution for newline as well, the exact same implementation! So I moved up the newline at index check and have it run the same function which updates our typingAttributes with an updated indent styling. Looks like it's working from my end! Should probably test it a bit longer but I need to put this down and come back with fresh eyes.

Should be good to review when you're ready though!

**Comment by danielsaidi** [comment]
Wow, that's great! I'll take a look tomorrow or the day after that 🎉

**Comment by jamesbradleym** [comment]
I've removed quite a bit of the tags code, there are still some remnants along with some additional code that I had been toying with as a workaround to the indent walls I was hitting before the last update. Will continue cleaning up and let you know when its pure indent updates!

**Comment by jamesbradleym** [comment]
@danielsaidi Ready for review! 👍🏻

**Comment by danielsaidi** [comment]
@jamesbradleym 

This PR looks absolutely amazing - such impressive work! I manage to make some changes to the toolbar, which cause some merge conflicts. I will fix the conflicts then merge the PR.

I however don't think the indent actions should be added to the toolbar by default, since the space is so limited on iPhone. I will instead add the actions to the the rich text format sheet, and figure out how to best add them to macOS.

The merge conflict was caused by some changes I made to the toolbar, where I have moved some init arguments to the style and also added a way to make it possible to modify the format sheet from the initializer. 

I used this new modifier to apply undimmed presentation detents to the sheet, so that you can edit the underlying text editor while the sheet is opened:

IMG_005F8893E34A-1

With all these additions, I think the 0.6 will be a quite nice update! :)

**Comment by jamesbradleym** [comment]
Fantastic, thanks for all your work! Definitely agree on conserving space with iOS, bit tricky!

**Comment by danielsaidi** [comment]
I redesigned the iOS/iPadOS format sheet, so that we have the indentation buttons there as well:

toolbar-stylegroup-segmented

**Pull request merged**
